@startuml
skinparam dpi 150
skinparam classAttributeIconSize 0
hide empty members

abstract class Account {
  # balance : double
  + Account(balance : double)
  + deposit(amount : double) : void
  + {abstract} withdraw(amount : double) : boolean
}

interface InterestBearing {
  + addInterest() : void
}

class ChequingAccount {
  - overdraftLimit : double
  + withdraw(amount : double) : boolean
}

class SavingsAccount {
  - rate : double
  + withdraw(amount : double) : boolean
  + addInterest() : void
}

ChequingAccount --|> Account
SavingsAccount --|> Account
SavingsAccount ..|> InterestBearing
@enduml
